FROM anapsix/alpine-java:jdk8

ARG BA_DEMO_SERVICES_SERVER_PORT
ENV BA_DEMO_SERVICES_SERVER_PORT ${BA_DEMO_SERVICES_SERVER_PORT:-9000}
ARG BA_DEMO_SERVICES_LOG_DIR
ENV BA_DEMO_SERVICES_LOG_DIR ${BA_DEMO_SERVICES_LOG_DIR:-/var/log/ba/demoapp}

WORKDIR /opt/demoapp
COPY target/springboot-demo-0.0.1-SNAPSHOT.jar springboot-demo.jar
RUN mkdir -p ${BA_DEMO_SERVICES_LOG_DIR}

EXPOSE ${BA_DEMO_SERVICES_SERVER_PORT}

CMD java \
    -jar \
    springboot-demo.jar
